// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'form': string;
  'option': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
