// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'contentParallax': string;
  'contentText': string;
  'contentText_first': string;
  'contentText_second': string;
  'inline': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
