// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form_loading': string;
  'img': string;
  'red_background': string;
  'text_loading': string;
}
export const cssExports: CssExports;
export default cssExports;
