// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align_center': string;
  'inline': string;
  'pagination': string;
  'pagination_page': string;
  'pokemons_block': string;
  'search_field': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
