// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form_404': string;
  'red_background': string;
  'text': string;
  'text_404': string;
  'trio': string;
}
export const cssExports: CssExports;
export default cssExports;
